2022-06-23 23:06:00,424 INFO    MainThread:25072 [wandb_setup.py:_flush():76] Loading settings from /home/scau/.config/wandb/settings
2022-06-23 23:06:00,424 INFO    MainThread:25072 [wandb_setup.py:_flush():76] Loading settings from /media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/wandb/settings
2022-06-23 23:06:00,424 INFO    MainThread:25072 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-23 23:06:00,424 INFO    MainThread:25072 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': '/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/train.py'}
2022-06-23 23:06:00,424 INFO    MainThread:25072 [wandb_setup.py:_flush():76] Applying login settings: {'login_timeout': 30}
2022-06-23 23:06:00,424 INFO    MainThread:25072 [wandb_init.py:_log_setup():428] Logging user logs to /media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/wandb/run-20220623_230600-38mg0eyo/logs/debug.log
2022-06-23 23:06:00,424 INFO    MainThread:25072 [wandb_init.py:_log_setup():429] Logging internal logs to /media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/wandb/run-20220623_230600-38mg0eyo/logs/debug-internal.log
2022-06-23 23:06:00,425 INFO    MainThread:25072 [wandb_init.py:init():462] calling init triggers
2022-06-23 23:06:00,425 INFO    MainThread:25072 [wandb_init.py:init():466] wandb.init called with sweep_config: {}
config: {}
2022-06-23 23:06:00,425 INFO    MainThread:25072 [wandb_init.py:init():515] starting backend
2022-06-23 23:06:00,425 INFO    MainThread:25072 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-06-23 23:06:00,434 INFO    MainThread:25072 [backend.py:ensure_launched():217] starting backend process...
2022-06-23 23:06:00,437 INFO    MainThread:25072 [backend.py:ensure_launched():222] started backend process with pid: 25105
2022-06-23 23:06:00,438 INFO    MainThread:25072 [wandb_init.py:init():525] backend started and connected
2022-06-23 23:06:00,444 INFO    MainThread:25072 [wandb_init.py:init():596] updated telemetry
2022-06-23 23:06:00,445 INFO    MainThread:25072 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-06-23 23:06:30,446 INFO    MainThread:25072 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2022-06-23 23:06:30,446 ERROR   MainThread:25072 [wandb_init.py:init():636] backend process timed out
2022-06-23 23:06:30,447 ERROR   MainThread:25072 [wandb_init.py:init():647] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-06-24 08:15:44,652 WARNING MainThread:25072 [wandb_init.py:init():1020] interrupted
Traceback (most recent call last):
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/wandb-0.12.19-py3.7.egg/wandb/sdk/wandb_init.py", line 999, in init
    run = wi.init()
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/wandb-0.12.19-py3.7.egg/wandb/sdk/wandb_init.py", line 651, in init
    backend.cleanup()
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/wandb-0.12.19-py3.7.egg/wandb/sdk/backend/backend.py", line 248, in cleanup
    self.wandb_process.join()
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/multiprocessing/popen_fork.py", line 48, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
